%% vim:ft=erlang:

case os:getenv("COVERALLS") of
    false -> CONFIG;
    JobId ->
        %% coveralls.io.
        [{plugins, [coveralls]}
        ,{cover_enabled, true}
        ,{cover_print_enabled, true}
        ,{cover_export_enabled, true}
        ,{coveralls_coverdata, "_build/test/cover/eunit.coverdata"}
        ,{coveralls_service_name, "travis-ci"}
        ,{coveralls_service_job_id, JobId}
         |CONFIG
        ]
end.
