#!/bin/sh

set -e

scriptdir=$(cd $(dirname $0) && pwd)
rootdir=$(cd $scriptdir/.. && pwd)
eunitdir="$rootdir/.eunit"
testdir="$rootdir/test"

mkdir -p "$testdir" "$eunitdir"

export srcdir="$scriptdir"
export builddir="$scriptdir"
export top_srcdir="$rootdir"
export top_builddir="$rootdir"

# Generate fake .app file...
sed -E -e 's/\{vsn,.*/{vsn, "rebar eunit"},/'				\
 < $rootdir/ebin/yamerl.app.in.in					\
 > $eunitdir/yamerl.app

tests="parsing construction wrapper examples"
for testname in $tests; do
	$srcdir/gen-test-erlang-module					\
	 $srcdir/template.erl						\
	 $srcdir/data/$testname						\
	 > "$testdir/$testname.erl"
done
